# Generated by Django 3.1.4 on 2022-04-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='profile',
            new_name='company',
        ),
    ]
