# Generated by Django 3.1.4 on 2022-04-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0003_auto_20220414_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customersapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customersapp.agent'),
        ),
    ]
