# Generated by Django 3.1.4 on 2022-04-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0007_category_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customersapp.category'),
        ),
    ]
